'use client';
import {useEffect,useRef,useState} from 'react';import {io} from 'socket.io-client';import ChatPanel from '@/components/ChatPanel';
const roles=['USER','MODERATOR','DJ','ADMIN','WEBMASTER'];
export default function DJ(){
 const [me,setMe]=useState(null),[radio,setRadio]=useState({live:false,title:'101dunyasi.com Otomatik Yayın',announcement:''}),[users,setUsers]=useState([]),[tab,setTab]=useState('studio'),[title,setTitle]=useState('101dunyasi.com Canlı Yayın'),[announcement,setAnnouncement]=useState(''),[mic,setMic]=useState(false),[msg,setMsg]=useState(''),[music,setMusic]=useState([]),[upload,setUpload]=useState(null),[requests,setRequests]=useState([]),[playing,setPlaying]=useState(null);
 const stream=useRef(null),socket=useRef(null),peers=useRef(new Map()),file=useRef(null);
 const loadMusic=()=>fetch('/api/dj/music').then(r=>r.json()).then(x=>setMusic(x.music||[]));
 useEffect(()=>{fetch('/api/auth/me').then(r=>r.json()).then(x=>setMe(x.user));fetch('/api/dj/status').then(r=>r.json()).then(x=>{setRadio(x);setTitle(x.title||'101dunyasi.com Canlı Yayın');setAnnouncement(x.announcement||'')});loadMusic();fetch('/api/requests').then(r=>r.json()).then(x=>setRequests(x.requests||[]));const s=io({withCredentials:true});socket.current=s;s.on('presence',p=>setUsers(p.users||[]));s.on('radio:status',setRadio);s.on('rtc:listener',async({listenerId})=>{if(stream.current)await call(listenerId)});return()=>{s.close();stream.current?.getTracks().forEach(t=>t.stop());peers.current.forEach(p=>p.close())}},[]);
 function makePeer(id){if(peers.current.has(id))return peers.current.get(id);const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});pc.onicecandidate=e=>e.candidate&&socket.current?.emit('rtc:ice',{target:id,candidate:e.candidate});if(stream.current)stream.current.getTracks().forEach(t=>pc.addTrack(t,stream.current));peers.current.set(id,pc);return pc}
 async function call(id){try{const pc=makePeer(id);const offer=await pc.createOffer();await pc.setLocalDescription(offer);socket.current?.emit('rtc:offer',{target:id,description:pc.localDescription})}catch{}}
 async function toggleMic(){if(mic){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;peers.current.forEach(p=>p.close());peers.current.clear();setMic(false);setMsg('Mikrofon kapatıldı.');return}try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});setMic(true);setMsg('Mikrofon açık. Dinleyicilere bağlanılıyor...');for(const u of users)if(u.role==='USER'&&u.socketId)await call(u.socketId)}catch{setMsg('Mikrofon izni verilmedi.')}}
 async function saveLive(next){const r=await fetch('/api/dj/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({live:next,title,announcement})});const x=await r.json();if(!r.ok){setMsg(x.error||'İşlem başarısız');return}setRadio(x);socket.current?.emit('dj:state',x);setMsg(next?'🔴 Yayın başladı.':'⏹ Yayın durdu.');if(next&&mic)for(const u of users)if(u.role==='USER'&&u.socketId)await call(u.socketId)}
 async function saveText(){const r=await fetch('/api/dj/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({live:radio.live,title,announcement})});const x=await r.json();if(r.ok){setRadio(x);socket.current?.emit('dj:state',x);setMsg('Yayın bilgileri güncellendi.')}}
 async function uploadMusic(e){e.preventDefault();if(!upload)return;const fd=new FormData();fd.append('file',upload);const r=await fetch('/api/dj/music',{method:'POST',body:fd});const x=await r.json();if(!r.ok){setMsg(x.error);return}setMusic(v=>[...v,x.music]);setUpload(null);if(file.current)file.current.value='';setMsg('🎵 Parça müzik arşivine eklendi.')}
 async function delMusic(id){if(!confirm('Parça silinsin mi?'))return;const r=await fetch('/api/dj/music',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(r.ok)setMusic(v=>v.filter(x=>x.id!==id))}
 async function reqStatus(id,status){await fetch('/api/admin/requests',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});setRequests(v=>v.map(r=>r.id===id?{...r,status}:r))}
 if(me&& !['DJ','ADMIN','WEBMASTER'].includes(me.role))return <main><div className="panel" style={{maxWidth:600,margin:'80px auto'}}>DJ yetkisi gerekli. <a href="/">Radyoya dön</a></div></main>;
 return <main className="admin"><header className="siteHeader"><div><span className="brand">101<span>dunyasi</span></span><div className="sub">PROFESYONEL DJ STÜDYOSU</div></div><div className="top"><span>🟢 {users.filter(u=>u.role==='USER').length} dinleyici</span><a className="navBtn" href="/">← Canlı Oda</a></div></header>
 <div className="adminWrap"><div className="studioHero"><div><div className={radio.live?'live liveOn':'live'}>{radio.live?'● YAYINDASIN':'○ STÜDYO HAZIR'}</div><h1>DJ Kontrol Merkezi</h1><p>Canlı odadan çıkmadan yayın, müzik arşivi, istekler ve dinleyicileri yönet.</p></div><div className="vu">🎚️</div></div>
 <div className="workspaceTabs">{[['studio','🎙️ Stüdyo'],['music','🎵 Müzik Arşivi'],['requests','📨 İstekler'],['listeners','👥 Dinleyiciler']].map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}<a className="navBtn" href="/">Sohbete dön</a></div>
 {tab==='studio'&&<div className="studioGrid"><section className="panel"><h2>📻 Yayın Kumandası</h2><label>Yayın başlığı<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Duyuru<textarea value={announcement} onChange={e=>setAnnouncement(e.target.value)}/></label><div className="row"><button onClick={saveText}>Bilgileri Kaydet</button><button className={radio.live?'danger':''} onClick={()=>saveLive(!radio.live)}>{radio.live?'⏹ Yayını Durdur':'▶ Yayını Başlat'}</button></div><div className="notice">{radio.live?'Canlı DJ modu aktif.':'Otomatik yayın modu aktif. DJ bağlantısı koparsa yedek müzik devreye girer.'}</div></section><section className="panel"><h2>🎙️ Mikrofon</h2><p className="muted">Tarayıcı mikrofonunu açıp dinleyicilere canlı ses gönder.</p><button className={mic?'big danger':'big'} onClick={toggleMic}>{mic?'⏹ Mikrofonu Kapat':'🎤 Mikrofonu Aç'}</button><div className="meter"><span style={{width:mic?'72%':'8%'}}/></div>{msg&&<div className="notice">{msg}</div>}</section><section className="panel"><h2>⚡ Hızlı Yayın</h2><button className="big" onClick={()=>setTab('music')}>🎵 Müzik Arşivine Git</button><button className="big" onClick={()=>setTab('requests')}>📨 İstek Kuyruğu ({requests.filter(r=>r.status==='pending').length})</button><button className="big" onClick={()=>setTab('listeners')}>👥 Dinleyicileri Gör</button></section><section className="panel"><h2>🛟 Kesintisiz Yayın</h2><p className="muted">DJ bağlantısı kesildiğinde sunucu yayını otomatik olarak AUTO moduna geçirir. Arşivdeki parçalar ana sayfadaki otomatik oynatıcıdan sırayla çalınır.</p><b>{music.length} parça hazır</b></section></div>}
 {tab==='music'&&<section className="panel"><div className="panelTitle"><h2>🎵 Müzik Arşivi</h2><span>{music.length} parça</span></div><p className="muted">DJ müziğini buraya yükler. MP3, WAV, OGG, WEBM ve M4A desteklenir. Yüklenen parçalar otomatik yayın kuyruğuna dahil edilir.</p><form onSubmit={uploadMusic} className="uploadBox"><input ref={file} type="file" accept="audio/*" onChange={e=>setUpload(e.target.files?.[0]||null)}/><button>⬆️ Arşive Yükle</button></form><div className="musicGrid">{music.map(m=><div className="musicCard" key={m.id}><div className="musicIcon">♫</div><div><b>{m.name}</b><small>{Math.ceil(m.size/1024/1024*10)/10} MB · {m.uploadedBy}</small></div><div className="actions"><button onClick={()=>setPlaying(m)}>▶</button><button className="danger" onClick={()=>delMusic(m.id)}>Sil</button></div></div>)}</div>{!music.length&&<div className="empty small">Henüz müzik yüklenmedi.</div>}{playing&&<div className="stickyPlayer"><b>🎧 {playing.name}</b><audio controls autoPlay src={playing.url}/></div>}</section>}
 {tab==='requests'&&<section className="panel"><div className="panelTitle"><h2>📨 Şarkı İstek Merkezi</h2><span>{requests.filter(r=>r.status==='pending').length} bekliyor</span></div>{requests.map(r=><div className="requestAdmin" key={r.id}><b>{r.song}</b><small>{r.username} · {r.status}</small><div className="actions"><button onClick={()=>reqStatus(r.id,'approved')}>Onayla</button><button onClick={()=>reqStatus(r.id,'played')}>Çalındı</button><button className="danger" onClick={()=>reqStatus(r.id,'rejected')}>Reddet</button></div></div>)}{!requests.length&&<div className="empty small">İstek kuyruğu boş.</div>}</section>}
 {tab==='listeners'&&<section className="panel"><div className="panelTitle"><h2>👥 Dinleyiciler</h2><span>{users.filter(u=>u.role==='USER').length} dinleyici</span></div><div className="proUserGrid">{users.filter(u=>u.role!=='DJ').map(u=><div className="proUser" key={u.id}><span className="avatar">{u.username[0]?.toUpperCase()}</span><div><b>{u.username}</b><small>{roles.includes(u.role)?u.role:'USER'}</small></div><span className="onlineDot">●</span></div>)}</div></section>}
 <div className="djBottomGrid"><ChatPanel compact/><section className="panel"><h2>🟢 Canlı Durum</h2><div className="liveSummary"><b>{radio.live?'DJ CANLI':'OTOMATİK YAYIN'}</b><span>{radio.dj||'Sistem'}</span><span>{users.filter(u=>u.role==='USER').length} dinleyici</span></div><p className="muted">DJ çalışma alanını kullanırken sohbeti açık tutabilir, istekleri ve dinleyicileri aynı ekrandan takip edebilirsin.</p></section></div></div></main>}
