import {NextResponse} from 'next/server';
import {getUserFromCookies} from '@/lib/auth';
import {readData,writeData} from '@/lib/store';
const ok=u=>u?.role==='WEBMASTER';
export async function GET(req){const u=getUserFromCookies(req.cookies);if(!ok(u))return NextResponse.json({error:'Webmaster yetkisi gerekli.'},{status:403});const d=readData();return NextResponse.json({sources:d.radioSources||[],playlists:d.playlists||[],schedules:d.schedules||[]})}
export async function POST(req){const u=getUserFromCookies(req.cookies);if(!ok(u))return NextResponse.json({error:'Webmaster yetkisi gerekli.'},{status:403});const b=await req.json();const d=readData();
 if(b.type==='source'){const name=String(b.name||'').trim();const url=String(b.url||'').trim();if(!name||!/^https?:\/\//i.test(url))return NextResponse.json({error:'Kaynak adı ve geçerli http/https stream URL gerekli.'},{status:400});const item={id:String(Date.now()),name,url,fmFrequency:String(b.fmFrequency||'').slice(0,30),kind:String(b.kind||'HLS'),priority:Number(b.priority||1),enabled:b.enabled!==false,createdAt:new Date().toISOString()};d.radioSources=(d.radioSources||[]).filter(x=>x.url!==url);d.radioSources.push(item);d.radioSources.sort((a,b)=>a.priority-b.priority);d.auditLogs.push({id:Date.now(),actor:u.username,action:'radio_source_add',target:name,at:new Date().toISOString()});writeData(d);return NextResponse.json({item});}
 if(b.type==='playlist'){const name=String(b.name||'').trim();if(!name)return NextResponse.json({error:'Playlist adı gerekli.'},{status:400});const item={id:String(Date.now()),name,trackIds:Array.isArray(b.trackIds)?b.trackIds.map(String):[],shuffle:!!b.shuffle,repeat:b.repeat||'all',enabled:b.enabled!==false};d.playlists=(d.playlists||[]).filter(x=>x.name!==name);d.playlists.push(item);writeData(d);return NextResponse.json({item});}
 if(b.type==='schedule'){const item={id:String(Date.now()),day:Number(b.day||0),start:String(b.start||'00:00'),end:String(b.end||'23:59'),dj:String(b.dj||''),playlistId:String(b.playlistId||''),enabled:b.enabled!==false};d.schedules.push(item);writeData(d);return NextResponse.json({item});}
 return NextResponse.json({error:'Geçersiz kayıt türü.'},{status:400})}
export async function PATCH(req){const u=getUserFromCookies(req.cookies);if(!ok(u))return NextResponse.json({error:'Webmaster yetkisi gerekli.'},{status:403});const b=await req.json(),d=readData();if(b.type==='settings'){if(typeof b.autoFallback==='boolean')d.settings.autoFallback=b.autoFallback;if(Number.isFinite(Number(b.fallbackDelaySec)))d.settings.fallbackDelaySec=Math.max(1,Math.min(60,Number(b.fallbackDelaySec)));if(typeof b.sourceId==='string')d.radio.fallbackSourceId=b.sourceId;writeData(d);return NextResponse.json({settings:d.settings,radio:d.radio})}if(b.type==='source'){const x=(d.radioSources||[]).find(x=>x.id===String(b.id));if(!x)return NextResponse.json({error:'Kaynak bulunamadı.'},{status:404});Object.assign(x,{name:b.name!==undefined?String(b.name).slice(0,100):x.name,url:b.url!==undefined?String(b.url):x.url,fmFrequency:b.fmFrequency!==undefined?String(b.fmFrequency).slice(0,30):x.fmFrequency,kind:b.kind!==undefined?String(b.kind):x.kind,priority:b.priority!==undefined?Number(b.priority):x.priority,enabled:b.enabled!==undefined?!!b.enabled:x.enabled});d.radioSources.sort((a,b)=>a.priority-b.priority);writeData(d);return NextResponse.json({item:x})}return NextResponse.json({error:'Geçersiz işlem.'},{status:400})}
export async function DELETE(req){const u=getUserFromCookies(req.cookies);if(!ok(u))return NextResponse.json({error:'Webmaster yetkisi gerekli.'},{status:403});const b=await req.json(),d=readData();if(b.type==='source')d.radioSources=(d.radioSources||[]).filter(x=>x.id!==String(b.id));if(b.type==='playlist')d.playlists=(d.playlists||[]).filter(x=>x.id!==String(b.id));if(b.type==='schedule')d.schedules=(d.schedules||[]).filter(x=>x.id!==String(b.id));writeData(d);return NextResponse.json({ok:true})}
