'use client';
import {useEffect,useMemo,useState} from 'react';
const roles=['USER','MODERATOR','DJ','ADMIN','WEBMASTER'];
const perms=['users.manage','dj.manage','moderation','chat.delete','chat.clear','radio.live','music.manage','requests.manage','requests.create'];
export default function Admin(){
 const[me,setMe]=useState(null),[users,setUsers]=useState([]),[stats,setStats]=useState(null),[requests,setRequests]=useState([]),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[settings,setSettings]=useState({autoFallback:true,requestEnabled:true}),[msg,setMsg]=useState('');
 async function load(){const m=await fetch('/api/auth/me').then(r=>r.json());setMe(m.user);if(!['ADMIN','WEBMASTER'].includes(m.user?.role))return;const [u,s,r]=await Promise.all([fetch('/api/admin/users'),fetch('/api/admin/stats'),fetch('/api/requests')]);const uj=await u.json(),sj=await s.json(),rj=await r.json();setUsers(uj.users||[]);setStats(sj);setSettings(sj.settings||settings);setRequests(rj.requests||[])}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>users.filter(u=>u.username.toLowerCase().includes(search.toLowerCase())),[users,search]);
 async function saveUser(id,p){const r=await fetch('/api/admin/user',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...p})});const x=await r.json();setMsg(r.ok?'Kullanıcı kaydedildi.':x.error);if(r.ok){setSelected(null);load()}}
 async function req(id,status){const r=await fetch('/api/admin/requests',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});const x=await r.json();setMsg(r.ok?'İstek güncellendi.':x.error);load()}
 async function saveSettings(){const r=await fetch('/api/admin/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});const x=await r.json();setMsg(r.ok?'Ayarlar kaydedildi.':x.error)}
 if(!me)return <main className="setupPage"><section className="auth"><div className="brand center">101<span>dunyasi</span>.com</div><h2>Yükleniyor…</h2></section></main>;
 if(!['ADMIN','WEBMASTER'].includes(me.role))return <main className="setupPage"><section className="auth"><h2>Yetki gerekli</h2><a className="big linkButton" href="/">Ana Sayfa</a></section></main>;
 return <main className="admin"><header className="siteHeader"><div><span className="brand">101<span>dunyasi</span>.com</span><div className="sub">YÖNETİM MERKEZİ</div></div><div className="top"><span className="roleBadge">{me.role}</span><b>{me.username}</b><a className="navBtn" href="/">← Radyo</a></div></header><div className="adminWrap">
 <div className="adminIntro"><div><div className="eyebrow">CONTROL CENTER</div><h1>{me.role==='WEBMASTER'?'Yönetim Merkezi':'Admin Paneli'}</h1><p className="muted">Kullanıcı, DJ, moderasyon ve yayın operasyonu</p></div><button className="navBtn" onClick={load}>↻ Yenile</button></div>
 {msg&&<div className="notice">{msg}<button className="noticeClose" onClick={()=>setMsg('')}>×</button></div>}
 <div className="statsGrid"><Stat n={stats?.users||0} t="Kullanıcı"/><Stat n={stats?.djs||0} t="DJ"/><Stat n={stats?.admins||0} t="Admin"/><Stat n={stats?.moderators||0} t="Moderatör"/><Stat n={stats?.music||0} t="Müzik"/><Stat n={stats?.radio?.listeners||0} t="Çevrimiçi"/></div>
 <section className="panel"><div className="panelTitle"><h2>👥 Kullanıcılar</h2><span>{filtered.length}/{users.length}</span></div><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Kullanıcı ara…"/><button onClick={()=>setSearch('')}>Temizle</button></div><div className="userCards">{filtered.map(u=><button className="userAdminCard" key={u.id} onClick={()=>setSelected(u)}><span className="avatar">{u.username[0]?.toUpperCase()}</span><span className="userAdminMain"><b className={u.gold?'goldName':''}>{u.username}</b><small>{u.role} · {u.status}</small></span><span className="userAdminMeta">{u.gold?'⭐':''}<i>›</i></span></button>)}</div></section>
 <div className="adminCards"><section className="panel"><h2>🎵 Şarkı İstekleri</h2>{requests.slice(0,20).map(r=><div className="requestAdmin" key={r.id}><b>{r.song}</b><small>{r.username} · {r.status}</small><div className="actions"><button onClick={()=>req(r.id,'approved')}>Onayla</button><button onClick={()=>req(r.id,'played')}>Çalındı</button><button className="danger" onClick={()=>req(r.id,'rejected')}>Reddet</button></div></div>)}</section><section className="panel"><h2>📻 Yayın</h2><div className="liveBox"><b>{stats?.radio?.live?'🔴 DJ CANLI':'🎵 OTOMATİK YAYIN'}</b><span>{stats?.radio?.dj||'101dunyasi.com Otomatik Yayın'}</span><small>{stats?.radio?.currentTrack?.name||stats?.radio?.title}</small></div><label className="check"><input type="checkbox" checked={!!settings.autoFallback} onChange={e=>setSettings({...settings,autoFallback:e.target.checked})}/> DJ kopunca otomatik yayın</label><label className="check"><input type="checkbox" checked={!!settings.requestEnabled} onChange={e=>setSettings({...settings,requestEnabled:e.target.checked})}/> Şarkı istekleri açık</label><button className="big" onClick={saveSettings}>💾 Kaydet</button></section></div>
 </div>{selected&&<UserModal user={selected} me={me} onClose={()=>setSelected(null)} onSave={saveUser}/>}</main>
}
function Stat({n,t}){return <div className="stat"><b>{n}</b><span>{t}</span></div>}
function UserModal({user,me,onClose,onSave}){
 const[role,setRole]=useState(user.role),[status,setStatus]=useState(user.status||'active'),[gold,setGold]=useState(!!user.gold),[password,setPassword]=useState(''),[bio,setBio]=useState(user.bio||''),[permissions,setPermissions]=useState(user.permissions||[]),[saving,setSaving]=useState(false);
 async function save(){setSaving(true);await onSave(user.id,{role,status,gold,bio,password:password||undefined,permissions});setSaving(false)}
 return <div className="modalBackdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="userPermModal"><div className="workspaceHead"><div><b>👤 {user.username}</b><small>Hesap ve yetki yönetimi</small></div><button className="x" onClick={onClose}>×</button></div><div className="modalGrid"><div className="panel"><h3>Hesap</h3><label>Rol<select value={role} onChange={e=>setRole(e.target.value)} disabled={me.role==='ADMIN'&&['ADMIN','WEBMASTER'].includes(user.role)}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label>Durum<select value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Aktif</option><option value="banned">Banlı</option></select></label><label>Yeni şifre<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Değiştirmek istemiyorsan boş bırak"/></label><label className="check"><input type="checkbox" checked={gold} onChange={e=>setGold(e.target.checked)}/> ⭐ GOLD</label><label>Biyografi<textarea value={bio} onChange={e=>setBio(e.target.value)}/></label></div><div className="panel"><h3>Özel Yetkiler</h3>{perms.map(p=><label className="check" key={p}><input type="checkbox" checked={permissions.includes(p)} onChange={e=>setPermissions(e.target.checked?[...new Set([...permissions,p])]:permissions.filter(x=>x!==p))}/>{p}</label>)}</div></div><div className="modalActions"><button onClick={onClose}>İptal</button><button className="big" disabled={saving} onClick={save}>💾 Kaydet</button></div></section></div>
}
