'use client';import{useEffect,useState}from'react';
export default function Admin(){const[users,setUsers]=useState([]),[stats,setStats]=useState(null),[requests,setRequests]=useState([]),[err,setErr]=useState(''),[settings,setSettings]=useState({autoFallback:true,requestEnabled:true}),[busy,setBusy]=useState('');
 async function load(){try{const [u,s,r]=await Promise.all([fetch('/api/admin/users'),fetch('/api/admin/stats'),fetch('/api/requests')]);const uj=await u.json(),sj=await s.json(),rj=await r.json();if(!u.ok)throw Error(uj.error);setUsers(uj.users);if(s.ok){setStats(sj);setSettings(sj.settings||{autoFallback:true,requestEnabled:true})}setRequests(rj.requests||[])}catch(e){setErr(e.message)}}useEffect(()=>{load()},[]);
 async function update(id,patch){setBusy(id);const r=await fetch('/api/admin/user',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...patch})});const x=await r.json();if(!r.ok)alert(x.error);await load();setBusy('')};async function remove(id){if(!confirm('Bu kullanıcı silinsin mi?'))return;await fetch('/api/admin/user',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});load()};async function reqStatus(id,status){await fetch('/api/admin/requests',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});load()};async function saveSettings(){const r=await fetch('/api/admin/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});const x=await r.json();if(!r.ok)alert(x.error);else alert('Ayarlar kaydedildi.')}
 return <main className="admin"><header className="siteHeader"><div><span className="brand">101<span>dunyasi</span></span><div className="sub">YÖNETİM MERKEZİ</div></div><div className="top"><a className="navBtn" href="/">← Radyo</a><a className="navBtn" href="/dj">DJ Stüdyosu</a></div></header><div className="adminWrap"><div className="adminIntro"><div className="eyebrow">CONTROL CENTER</div><h1>Admin Paneli</h1><p>Kullanıcı, DJ, istek, moderasyon ve yayın ayarları.</p></div>{err&&<div className="error">{err}</div>}{stats&&<div className="statsGrid"><Stat n={stats.users} t="Kullanıcı"/><Stat n={stats.djs} t="DJ"/><Stat n={stats.admins} t="Admin"/><Stat n={stats.messages} t="Mesaj"/><Stat n={stats.banned} t="Engelli"/></div>}
 <section className="panel"><div className="panelTitle"><h2>👥 Kullanıcı Yönetimi</h2><span>{users.length} hesap</span></div><div className="tableWrap"><table><thead><tr><th>Kullanıcı</th><th>Rol</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.username}</b><small>{u.bio||'Biyografi yok'}</small></td><td><select value={u.role} disabled={busy===u.id} onChange={e=>update(u.id,{role:e.target.value})}><option>USER</option><option>MODERATOR</option><option>DJ</option><option>ADMIN</option></select></td><td><span className={u.status==='banned'?'status bad':'status good'}>{u.status==='banned'?'ENGELLİ':'AKTİF'}</span></td><td className="actions"><button onClick={()=>update(u.id,{status:u.status==='banned'?'active':'banned'})}>{u.status==='banned'?'Engeli Aç':'Engelle'}</button><button className="danger" onClick={()=>remove(u.id)}>Sil</button></td></tr>)}</tbody></table></div></section>
 <div className="adminCards"><section className="panel"><h2>🎵 Şarkı İstekleri</h2>{requests.slice(0,30).map(r=><div className="requestAdmin" key={r.id}><b>{r.song}</b><small>{r.username} · {r.status}</small><div className="actions"><button onClick={()=>reqStatus(r.id,'approved')}>Onayla</button><button onClick={()=>reqStatus(r.id,'played')}>Çalındı</button><button className="danger" onClick={()=>reqStatus(r.id,'rejected')}>Reddet</button></div></div>)}{!requests.length&&<p className="muted">Henüz istek yok.</p>}</section><section className="panel"><h2>⚙️ Yayın Ayarları</h2><label className="check"><input type="checkbox" checked={!!settings.autoFallback} onChange={e=>setSettings({...settings,autoFallback:e.target.checked})}/> DJ bağlantısı kesilince otomatik müzik</label><label className="check"><input type="checkbox" checked={!!settings.requestEnabled} onChange={e=>setSettings({...settings,requestEnabled:e.target.checked})}/> Şarkı isteklerini aç</label><button className="big" onClick={saveSettings}>Ayarları Kaydet</button><p className="muted">Otomatik yayın, sunucu DJ soket bağlantısını kaybettiğinde devreye girer.</p></section></div>
 <section className="adminCards"><div className="panel"><h2>📻 Radyo Durumu</h2><p>{stats?.radio?.live?'🔴 DJ CANLI':'🎵 OTOMATİK YAYIN'}</p><p><b>DJ:</b> {stats?.radio?.dj||'—'}</p><p><b>Başlık:</b> {stats?.radio?.title||'—'}</p></div><div className="panel"><h2>🛡️ Moderasyon</h2><p className="muted">DJ ve admin mesaj silebilir; admin kullanıcı rolü, ban ve hesap yönetimini yapabilir.</p><a className="big linkButton" href="/">Canlı Odayı Aç</a></div></section></div></main>}
function Stat({n,t}){return <div className="stat"><b>{n}</b><span>{t}</span></div>}
