const http=require('http');const next=require('next');const {Server}=require('socket.io');const jwt=require('jsonwebtoken');const {readData,writeData}=require('./lib/store');
const dev=process.env.NODE_ENV!=='production',app=next({dev}),handle=app.getRequestHandler(),port=Number(process.env.PORT||3000),secret=process.env.JWT_SECRET||'dev-secret-change-me';
function userFromSocket(socket){const a=socket.handshake.auth?.token,c=socket.handshake.headers?.cookie||'',ct=c.match(/(?:^|;\s*)token=([^;]+)/)?.[1],t=a||ct;if(!t)return null;try{return jwt.verify(decodeURIComponent(t),secret)}catch{return null}}
const clean=u=>u?{id:u.id,username:u.username,role:u.role,gold:!!u.gold}:null;
app.prepare().then(()=>{const hs=http.createServer((req,res)=>handle(req,res));const io=new Server(hs,{cors:{origin:true,credentials:true}});
function broadcastRadio(){io.to('radio').emit('radio:status',readData().radio)}
function setAutoFallback(reason){const d=readData();if(!d.settings.autoFallback)return;d.radio={...d.radio,live:false,mode:'AUTO',dj:null,title:'101dunyasi.com Otomatik Yayın',announcement:reason||'DJ bağlantısı kesildi. Otomatik yayın devam ediyor.',startedAt:null};writeData(d);io.to('radio').emit('radio:status',d.radio);io.to('radio').emit('rtc:stop')}
function presence(){const users=[];for(const s of io.sockets.sockets.values())if(s.data.user)users.push({...clean(s.data.user),socketId:s.id});const d=readData();d.radio.listeners=users.length;writeData(d);io.to('radio').emit('presence',{count:users.length,users});broadcastRadio()}
io.on('connection',socket=>{const user=userFromSocket(socket);socket.data.user=user;socket.join('radio');presence();if(user)socket.emit('session:user',clean(user));
if(user&&user.role!=='DJ'&&readData().radio.live)for(const s of io.sockets.sockets.values())if(s.data.user?.role==='DJ'&&s.id!==socket.id)s.emit('rtc:listener',{listenerId:socket.id});
socket.on('chat:send',({text})=>{if(!user||typeof text!=='string')return;const d=readData(),u=d.users.find(x=>x.id===user.id);if(!u||u.status==='banned')return;const cleanText=text.replace(/\s+/g,' ').trim().slice(0,500);if(!cleanText)return;const m={id:`${Date.now()}-${Math.random().toString(36).slice(2,7)}`,userId:user.id,username:user.username,role:user.role,text:cleanText,createdAt:new Date().toISOString()};d.messages.push(m);d.messages=d.messages.slice(-500);writeData(d);io.to('radio').emit('chat:message',m)});
socket.on('chat:delete',({id})=>{if(!user||!['MODERATOR','DJ','ADMIN','WEBMASTER'].includes(user.role))return;const d=readData();d.messages=d.messages.filter(m=>String(m.id)!==String(id));d.moderationLogs.push({id:Date.now(),actor:user.username,action:'delete_message',target:String(id),at:new Date().toISOString()});writeData(d);io.to('radio').emit('chat:deleted',{id})});
socket.on('chat:clear',()=>{if(!user||user.role!=='ADMIN')return;const d=readData();d.messages=[];d.moderationLogs.push({id:Date.now(),actor:user.username,action:'clear_chat',at:new Date().toISOString()});writeData(d);io.to('radio').emit('chat:cleared')});
socket.on('dj:state',p=>{if(!user||!['DJ','ADMIN','WEBMASTER'].includes(user.role))return;const d=readData();const live=!!p.live;d.radio={...d.radio,live,mode:live?'DJ':'AUTO',dj:live?user.username:null,title:String(p.title??d.radio.title).slice(0,120),announcement:String(p.announcement??d.radio.announcement).slice(0,300),disco:!!p.disco,startedAt:live?(d.radio.startedAt||new Date().toISOString()):null};writeData(d);broadcastRadio();if(!live)io.to('radio').emit('rtc:stop')});
socket.on('rtc:listener',({listenerId})=>{if(!listenerId)return;for(const s of io.sockets.sockets.values())if(s.data.user?.role==='DJ')s.emit('rtc:listener',{listenerId})});
socket.on('rtc:offer',({target,description})=>{if(!user||!['DJ','ADMIN'].includes(user.role)||!target||!description)return;io.to(target).emit('rtc:offer',{from:socket.id,description})});
socket.on('rtc:answer',({target,description})=>{if(!target||!description)return;io.to(target).emit('rtc:answer',{from:socket.id,description})});
socket.on('rtc:ice',({target,candidate})=>{if(target&&candidate)io.to(target).emit('rtc:ice',{from:socket.id,candidate})});
socket.on('disconnect',()=>{if(user?.role==='DJ'&&readData().radio.live){setAutoFallback(`DJ ${user.username} bağlantısını kaybetti. Otomatik müzik devrede.`)}io.to('radio').emit('rtc:peer-left',{socketId:socket.id});presence()});});
hs.listen(port,()=>console.log(`101dunyasi.com running on http://localhost:${port}`));});
