import {NextResponse} from 'next/server';
import {getUserFromCookies} from '@/lib/auth';
import {readData,writeData,audit} from '@/lib/store';
const ok=u=>u?.role==='WEBMASTER';
export async function GET(req){const u=getUserFromCookies(req.cookies);if(!ok(u))return NextResponse.json({error:'Webmaster yetkisi gerekli.'},{status:403});const d=readData();return NextResponse.json({playlists:d.playlists||[],schedules:d.schedules||[],radio:d.radio,settings:d.settings})}
export async function POST(req){const u=getUserFromCookies(req.cookies);if(!ok(u))return NextResponse.json({error:'Webmaster yetkisi gerekli.'},{status:403});const b=await req.json();const d=readData();
 if(b.type==='playlist'){const name=String(b.name||'').trim();if(!name)return NextResponse.json({error:'Playlist adı gerekli.'},{status:400});const item={id:String(Date.now()),name,trackIds:Array.isArray(b.trackIds)?b.trackIds.map(String):[],shuffle:!!b.shuffle,repeat:b.repeat||'all',enabled:b.enabled!==false};d.playlists=(d.playlists||[]).filter(x=>x.name!==name);d.playlists.push(item);audit(d,u.username,'playlist_save',name);writeData(d);return NextResponse.json({item});}
 if(b.type==='schedule'){const item={id:String(Date.now()),day:Number(b.day||0),start:String(b.start||'00:00'),end:String(b.end||'23:59'),dj:String(b.dj||''),playlistId:String(b.playlistId||''),enabled:b.enabled!==false};d.schedules.push(item);audit(d,u.username,'schedule_add',item.dj||'AUTO');writeData(d);return NextResponse.json({item});}
 return NextResponse.json({error:'Geçersiz kayıt türü.'},{status:400})}
export async function PATCH(req){const u=getUserFromCookies(req.cookies);if(!ok(u))return NextResponse.json({error:'Webmaster yetkisi gerekli.'},{status:403});const b=await req.json(),d=readData();if(b.type==='settings'){if(typeof b.autoFallback==='boolean')d.settings.autoFallback=b.autoFallback;if(Number.isFinite(Number(b.fallbackDelaySec)))d.settings.fallbackDelaySec=Math.max(1,Math.min(60,Number(b.fallbackDelaySec)));if(typeof b.slowModeSec==='number')d.settings.slowModeSec=Math.max(0,Math.min(30,b.slowModeSec));if(typeof b.badWords==='string')d.settings.badWords=b.badWords.slice(0,1000);audit(d,u.username,'radio_settings','radio');writeData(d);return NextResponse.json({settings:d.settings,radio:d.radio})}return NextResponse.json({error:'Geçersiz işlem.'},{status:400})}
export async function DELETE(req){const u=getUserFromCookies(req.cookies);if(!ok(u))return NextResponse.json({error:'Webmaster yetkisi gerekli.'},{status:403});const b=await req.json(),d=readData();if(b.type==='playlist')d.playlists=(d.playlists||[]).filter(x=>x.id!==String(b.id));if(b.type==='schedule')d.schedules=(d.schedules||[]).filter(x=>x.id!==String(b.id));audit(d,u.username,'radio_item_delete',String(b.id));writeData(d);return NextResponse.json({ok:true})}
