'use client';
import{useEffect,useRef,useState}from'react';import{io}from'socket.io-client';
const roleLabel={WEBMASTER:'Site Kurucusu',ADMIN:'Yönetici',DJ:'DJ',MODERATOR:'Moderatör',USER:'Dinleyici'};
const reactions=['❤️','😂','🔥','👏','🎉','😍','🎵','🙌'];
export default function RadioRoom(){
 const[user,setUser]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[auth,setAuth]=useState(false),[register,setRegister]=useState(false),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');
 const[radio,setRadio]=useState({live:false,mode:'AUTO',dj:null,title:'101dunyasi.com Otomatik Yayın',announcement:'',listeners:0,disco:false}),[online,setOnline]=useState([]),[mic,setMic]=useState(false),[notice,setNotice]=useState(''),[song,setSong]=useState(''),[requests,setRequests]=useState([]),[profile,setProfile]=useState(false),[bio,setBio]=useState(''),[workspace,setWorkspace]=useState(false),[wtab,setWtab]=useState('home'),[music,setMusic]=useState([]),[upload,setUpload]=useState(null),[playlistIndex,setPlaylistIndex]=useState(0),[fireworks,setFireworks]=useState(false);
 const socket=useRef(null),stream=useRef(null),peers=useRef(new Map()),audio=useRef(null),chat=useRef(null),uploadRef=useRef(null);
 const dj=user&&['DJ','ADMIN','WEBMASTER'].includes(user.role),mod=user&&['MODERATOR','DJ','ADMIN','WEBMASTER'].includes(user.role),wm=user?.role==='WEBMASTER';
 useEffect(()=>{fetch('/api/auth/me').then(r=>r.json()).then(x=>{setUser(x.user);setBio(x.user?.bio||'')});fetch('/api/messages').then(r=>r.json()).then(x=>setMessages(x.messages||[]));fetch('/api/dj/status').then(r=>r.json()).then(setRadio);fetch('/api/requests').then(r=>r.json()).then(x=>setRequests(x.requests||[]));fetch('/api/dj/music').then(r=>r.json()).then(x=>setMusic(x.music||[]));
 const s=io({withCredentials:true});socket.current=s;s.on('presence',p=>{setOnline(p.users||[]);setRadio(r=>({...r,listeners:p.count||0}))});s.on('radio:status',setRadio);s.on('chat:message',m=>setMessages(v=>[...v,m].slice(-500)));s.on('chat:deleted',({id})=>setMessages(v=>v.filter(m=>String(m.id)!==String(id))));s.on('chat:cleared',()=>setMessages([]));s.on('rtc:listener',async({listenerId})=>{if(stream.current)await call(listenerId)});s.on('rtc:offer',async({from,description})=>{try{const pc=peer(from);await pc.setRemoteDescription(description);const a=await pc.createAnswer();await pc.setLocalDescription(a);s.emit('rtc:answer',{target:from,description:pc.localDescription})}catch{}});s.on('rtc:answer',async({from,description})=>{try{await peers.current.get(from)?.setRemoteDescription(description)}catch{}});s.on('rtc:ice',async({from,candidate})=>{try{await peers.current.get(from)?.addIceCandidate(candidate)}catch{}});s.on('rtc:stop',()=>{if(audio.current)audio.current.srcObject=null;peers.current.forEach(p=>p.close());peers.current.clear();setNotice('DJ yayını sona erdi. Otomatik müzik devrede.')});return()=>{s.close();stream.current?.getTracks().forEach(t=>t.stop());peers.current.forEach(p=>p.close())}},[]);
 useEffect(()=>{if(chat.current)chat.current.scrollTop=chat.current.scrollHeight},[messages]);
 useEffect(()=>{if(!audio.current||radio.mode!=='AUTO')return;const list=music.length?music:[{id:'uploaded-default',name:'Blok3 - Sebebi Yar',url:'/music/blok3-sebebi-yar.mp3'}];const track=list[playlistIndex%list.length];audio.current.src=track.url;audio.current.play().catch(()=>setNotice('🎵 Otomatik müzik hazır. Tarayıcı başlatmak için oynat düğmesine basabilir.'))},[radio.mode,music,playlistIndex]);
 function nextTrack(){setPlaylistIndex(i=>i+1)}
 function peer(id){if(peers.current.has(id))return peers.current.get(id);const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});pc.onicecandidate=e=>e.candidate&&socket.current?.emit('rtc:ice',{target:id,candidate:e.candidate});pc.ontrack=e=>{if(audio.current&&e.streams[0]){audio.current.srcObject=e.streams[0];audio.current.play().catch(()=>{});setNotice('🔊 DJ sesi bağlandı.')}};if(stream.current)stream.current.getTracks().forEach(t=>pc.addTrack(t,stream.current));peers.current.set(id,pc);return pc}
 async function call(id){const pc=peer(id);const o=await pc.createOffer();await pc.setLocalDescription(o);socket.current?.emit('rtc:offer',{target:id,description:pc.localDescription})}
 async function toggleMic(){if(!dj){setAuth(true);return}if(mic){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;peers.current.forEach(p=>p.close());peers.current.clear();setMic(false);return}try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});setMic(true);setNotice('🎙️ Mikrofon açık.');for(const u of online)if(u.role==='USER'&&u.socketId)await call(u.socketId)}catch{setNotice('Mikrofon izni verilmedi.')}}
 async function toggleLive(){if(!dj){setAuth(true);return}const next=!radio.live;const r=await fetch('/api/dj/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({live:next,disco:radio.disco})});const x=await r.json();if(r.ok){setRadio(x);socket.current?.emit('dj:state',x);setNotice(next?'🔴 Canlı yayın başladı.':'🎵 Otomatik yayın başladı.')}}
 async function toggleDisco(){if(!dj)return;const next=!radio.disco;const x={...radio,disco:next};setRadio(x);socket.current?.emit('dj:state',x);setNotice(next?'🪩 Disko ışığı modu aktif.':'🪩 Disko ışığı modu kapalı.')}
 function send(e){e.preventDefault();if(text.trim()&&user)socket.current?.emit('chat:send',{text:text.trim()});setText('')}
 function react(e){if(!user){setAuth(true);return}socket.current?.emit('chat:send',{text:`${e}`});}
 async function requestSong(e){e.preventDefault();if(!user){setAuth(true);return}const r=await fetch('/api/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({song})}),x=await r.json();setNotice(r.ok?'🎵 İstek gönderildi.':x.error||'Hata');if(r.ok){setRequests(v=>[x.request,...v]);setSong('')}}
 async function uploadMusic(e){e.preventDefault();if(!upload)return;const fd=new FormData();fd.append('file',upload);const r=await fetch('/api/dj/music',{method:'POST',body:fd});const x=await r.json();if(!r.ok){setNotice(x.error);return}setMusic(v=>[...v,x.music]);setUpload(null);if(uploadRef.current)uploadRef.current.value='';setNotice('🎵 Müzik arşive eklendi.')}
 async function quickText(){if(!user)return;const r=await fetch('/api/dj/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({live:radio.live,title:radio.title,announcement:radio.announcement,disco:radio.disco})});if(r.ok)setNotice('Yayın bilgileri güncellendi.')}
 async function saveProfile(e){e.preventDefault();const r=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({bio})});if(r.ok){setUser(u=>({...u,bio}));setProfile(false);setNotice('Profil güncellendi.')}}
 function logout(){document.cookie='token=; Max-Age=0; path=/';location.reload()}
 function fireworksShow(){if(!user?.gold){setNotice('⭐ Havai fişek özelliği GOLD üyeler içindir.');return}setFireworks(true);setTimeout(()=>setFireworks(false),1700)}
 return <main className={radio.disco?'discoMode':''}><header className="siteHeader"><div><span className="brand">101<span>dunyasi</span>.com</span><div className="sub">CANLI DJ • OTOMATİK MÜZİK • SOHBET • TOPLULUK</div></div><div className="top"><span className="onlineDot">●</span><b>{radio.listeners||0}</b> çevrimiçi {user?<><span className={user.gold?'roleBadge goldBadge':'roleBadge'}>{user.gold?'⭐ GOLD':user.role}</span><b className={user.gold?'goldName':''}>{user.username}</b><button onClick={()=>setProfile(true)}>Profil</button>{mod&&<button className="navBtn" onClick={()=>setWorkspace(true)}>⚡ Çalışma Alanı</button>}<button onClick={logout}>Çıkış</button></>:<button onClick={()=>setAuth(true)}>Giriş / Kayıt</button>}</div></header>

 <section className="homeLayout">
 <div className="panel chatPanel chatPanelLarge"><div className="panelTitle"><h2>💬 Canlı Sohbet</h2><span>{messages.length} mesaj</span></div><div className="chat" ref={chat}>{messages.length?messages.map(m=><div className="msg" key={m.id}><div><b className={m.gold?'goldName':''}>{m.username}</b><small>{m.role}</small></div><span>{m.text}</span>{mod&&<button className="tiny danger" onClick={()=>socket.current?.emit('chat:delete',{id:m.id})}>Sil</button>}</div>):<div className="empty">Henüz mesaj yok.</div>}</div><div className="reactionBar">{reactions.map(e=><button type="button" key={e} onClick={()=>react(e)} title="Sohbete tepki gönder">{e}</button>)}{user?.gold&&<button type="button" className="goldBadge" onClick={fireworksShow}>🎆 Havai Fişek</button>}</div><form onSubmit={send} className="chatform"><input value={text} onChange={e=>setText(e.target.value)} placeholder={user?'Mesajını yaz...':'Giriş yaparak sohbete kat'} disabled={!user}/><button disabled={!user}>Gönder</button></form></div>

 <aside className="panel usersPanel"><div className="panelTitle"><h2>🟢 Çevrimiçi Kullanıcılar</h2><span>{online.length}</span></div><div className="userList">{online.length?online.map(u=><div className="userRow" key={u.id}><span className="avatar">{u.username[0]?.toUpperCase()}</span><div><b className={u.gold?'goldName':''}>{u.username}</b><small>{u.gold?'⭐ Gold Üye · ':''}{roleLabel[u.role]||u.role}</small></div><i>●</i></div>):<div className="empty small">Henüz giriş yapan yok.</div>}</div></aside>

 <div className="panel controls"><div className="panelTitle"><h2>🎵 Şarkı İsteği</h2><span>{requests.filter(r=>r.status==='pending').length} bekliyor</span></div><form onSubmit={requestSong} className="chatform"><input value={song} onChange={e=>setSong(e.target.value)} placeholder="Sanatçı - Şarkı"/><button>İstek Gönder</button></form><div className="requestList">{requests.slice(0,6).map(r=><div key={r.id}><b>{r.song}</b><small>{r.username} · {r.status}</small></div>)}</div>{notice&&<div className="notice">{notice}</div>}</div>
 </section>

 <div className="homeHero"><section className="hero"><div><div className={radio.live?'live liveOn':'live'}>{radio.live?'● DJ CANLI':'● OTOMATİK YAYIN'}</div><h1>{radio.title}</h1><p>{radio.live?`🎙️ ${radio.dj||'DJ'} yayında.`:'DJ bağlantısı olmadığında arşivdeki müzik otomatik olarak devam eder.'}</p><div className="heroActions"><button onClick={toggleLive}>{radio.live?'Yayını Kapat':'DJ Yayını'}</button>{dj&&<button className={mic?'danger':''} onClick={toggleMic}>{mic?'🎙️ Mikrofon Açık':'🎤 Mikrofon'}</button>}{dj&&<button onClick={toggleDisco}>{radio.disco?'🪩 Disko Modunu Kapat':'🪩 Disko Işıkları'}</button>}{mod&&<button onClick={()=>setWorkspace(true)}>⚡ Paneli Aç</button>}</div></div><div className="orb">🎧</div></section></div>
 <div className="announcement">📢 <b>Duyuru:</b> {radio.announcement||'101dunyasi.com topluluğuna hoş geldin!'}</div><audio ref={audio} controls autoPlay onEnded={nextTrack} className="audioPlayer"/>

 {workspace&&<div className="modal"><div className="workspaceModal"><div className="workspaceHead"><div><b>{wm?'👑 Webmaster':dj?'🎙️ DJ':'🛡️ Moderatör'} Çalışma Alanı</b><small>sohbet açık kalır, işlemler burada</small></div><button className="x" onClick={()=>setWorkspace(false)}>×</button></div>
 <div className="workspaceTabs">{wm&&[['home','Genel'],['site','Site'],['people','Roller']].map(x=><button className={wtab===x[0]?'active':''} onClick={()=>setWtab(x[0])} key={x[0]}>{x[1]}</button>)}{dj&&[['home','Yayın'],['music','Müzik'],['requests','İstekler'],['listeners','Dinleyiciler']].map(x=><button className={wtab===x[0]?'active':''} onClick={()=>setWtab(x[0])} key={x[0]}>{x[1]}</button>)}{user?.role==='MODERATOR'&&!dj&&<button className="active">Güvenlik</button>}</div>
 {dj&&wtab==='home'&&<div className="quickGrid"><section className="panel"><h3>📻 Yayın</h3><input value={radio.title} onChange={e=>setRadio({...radio,title:e.target.value})}/><textarea value={radio.announcement} onChange={e=>setRadio({...radio,announcement:e.target.value})}/><button onClick={quickText}>Bilgileri Kaydet</button><button onClick={toggleLive}>{radio.live?'⏹ Yayını Kapat':'▶ Yayını Başlat'}</button><button onClick={toggleMic}>{mic?'🎙️ Mikrofonu Kapat':'🎤 Mikrofonu Aç'}</button><button onClick={toggleDisco}>{radio.disco?'🪩 Disko Modunu Kapat':'🪩 Disko Işıkları'}</button></section><section className="panel"><h3>📈 Anlık Durum</h3><div className="listenerCount">{radio.listeners}<small> dinleyici</small></div><p className="muted">{radio.live?'Canlı DJ modu':'Otomatik yayın modu'}</p><p className="muted">Arşiv: {music.length} parça</p></section></div>}
 {dj&&wtab==='music'&&<section className="panel"><h3>🎵 DJ Müzik Arşivi</h3><p className="muted">MP3/WAV/OGG vb. parçaları buradan yükle. DJ yokken otomatik yayın sırayla çalar.</p><form onSubmit={uploadMusic} className="uploadBox"><input ref={uploadRef} type="file" accept="audio/*" onChange={e=>setUpload(e.target.files?.[0]||null)}/><button>⬆️ Yükle</button></form><div className="musicGrid">{music.map(m=><div className="musicCard" key={m.id}><div className="musicIcon">♫</div><div><b>{m.name}</b><small>{m.uploadedBy}</small></div><audio controls src={m.url}/></div>)}</div></section>}
 {dj&&wtab==='requests'&&<section className="panel"><h3>📨 İstek Kuyruğu</h3>{requests.map(r=><div className="requestAdmin" key={r.id}><b>{r.song}</b><small>{r.username} · {r.status}</small></div>)}</section>}
 {dj&&wtab==='listeners'&&<section className="panel"><h3>👥 Dinleyiciler</h3>{online.filter(u=>u.role==='USER').map(u=><div className="proUser" key={u.id}><span className="avatar">{u.username[0]}</span><b>{u.username}</b><span className="onlineDot">●</span></div>)}</section>}
 {wm&&<section className="panel"><h3>👑 Webmaster Merkezi</h3><p className="muted">Ayrıntılı yönetim, kullanıcılar, yayın kaynakları ve yetkiler.</p><a className="big linkButton" href="/webmaster">Webmaster Merkezi</a></section>}
 </div></div>}
 {profile&&<div className="modal"><form className="auth" onSubmit={saveProfile}><button type="button" className="x" onClick={()=>setProfile(false)}>×</button><h2>Profil</h2><p className="muted">{user?.username} · {user?.role}</p><textarea value={bio} onChange={e=>setBio(e.target.value)} placeholder="Biyografin"/><button>Kaydet</button></form></div>}
 {auth&&<div className="modal"><form onSubmit={async e=>{e.preventDefault();setError('');const r=await fetch(register?'/api/auth/register':'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})}),x=await r.json();if(!r.ok){setError(x.error||'İşlem başarısız');return}setUser(x.user);setAuth(false);location.reload()}} className="auth"><button type="button" className="x" onClick={()=>setAuth(false)}>×</button><div className="brand center">101<span>dunyasi</span>.com</div><h2>{register?'Yeni hesap':'Giriş yap'}</h2><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Kullanıcı adı" required/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Şifre" required/><button>{register?'Kayıt Ol':'Giriş Yap'}</button>{error&&<div className="error">{error}</div>}<a onClick={()=>setRegister(!register)}>{register?'Giriş yap':'Yeni hesap oluştur'}</a><div className="demo">Demo: webmaster/webmaster123 · admin/admin123 · dj/dj123 · moderator/mod123</div></form></div>}
 {fireworks&&<div className="fireworks" aria-hidden="true">{Array.from({length:28},(_,i)=><span className="firework" key={i} style={{left:`${10+(i*29)%80}%`,top:`${15+(i*17)%55}%`,'--dx':`${-120+(i*67)%240}px`,'--dy':`${-180+(i*31)%220}px`}}>{['🎆','✨','⭐','💥'][i%4]}</span>)}</div>}
 </main>
}
